---
# tasks file for setup_cinder_controller
- name: Create manila database
  shell: "{{ item }}"
  with_items:
    - mysql -u root -p{{ MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE manila; "
    - mysql -u root -p{{ MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON manila.* TO 'manila'@'localhost' IDENTIFIED BY '{{ MYSQL_MANILA_DBPASS }}'; "
    - mysql -u root -p{{ MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON manila.* TO 'manila'@'%' IDENTIFIED BY '{{ MYSQL_MANILA_DBPASS }}'; "

- name: Create user and add to role
  shell: "{{ item }}"
  with_items:
    - openstack user create --domain default --password {{ MANILA_PASSWORD }} manila
    - openstack role add --project service --user manila admin

- name: Create the service entity and API endpoints
  shell: "{{ item }}"
  with_items:
    - openstack service create --name manila --description "OpenStack Shared File Systems" share
    - openstack service create --name manilav2 --description "OpenStack Shared File Systems" sharev2
    - openstack endpoint create --region RegionOne share public http://controller:8786/v1/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne share internal http://controller:8786/v1/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne share admin http://controller:8786/v1/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne sharev2 public http://controller:8786/v2/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne sharev2 internal http://controller:8786/v2/%\(tenant_id\)s
    - openstack endpoint create --region RegionOne sharev2 admin http://controller:8786/v2/%\(tenant_id\)s

- name: Install manila controller packages
  apt: pkg={{ item }}
  with_items:
    - manila-api
    - manila-scheduler
    - python-manilaclient

- name: Configure manila.conf file
  ini_file:
      dest: /etc/manila/manila.conf
      section: "{{item.section}}"
      option:  "{{item.option}}"
      value:   "{{item.value}}"
      backup:  "{{item.backup}}"
  with_items:
    - { backup : yes,  section : 'database'             , option : 'connection'      , value: 'mysql+pymysql://manila:{{ MYSQL_MANILA_DBPASS }}@controller/manila'}
    - { backup : no,   section : 'DEFAULT'              , option : 'rpc_backend'     , value: 'rabbit'}
    - { backup : no,   section : 'oslo_messaging_rabbit', option : 'rabbit_host'     , value: '{{ RABBITMQ_SERVER }}'}
    - { backup : no,   section : 'oslo_messaging_rabbit', option : 'rabbit_userid'   , value: '{{ RABBITMQ_USER }}'}
    - { backup : no,   section : 'oslo_messaging_rabbit', option : 'rabbit_password' , value: '{{ RABBITMQ_PASSWORD }}'}
    - { backup : no,   section : 'DEFAULT'           , option : 'default_share_type' , value: 'default_share_type'}
    - { backup : no,   section : 'DEFAULT'           , option : 'rootwrap_config'    , value: '/etc/manila/rootwrap.conf'}
    - { backup : no,   section : 'DEFAULT'           , option : 'auth_strategy'      , value: 'keystone'}
    - { backup : no,   section : 'keystone_authtoken', option : 'auth_uri'           , value : 'http://{{ KEYSTONE_SERVER_NAME }}:5000'}
    - { backup : no,   section : 'keystone_authtoken', option : 'auth_url'           , value : 'http://{{ KEYSTONE_SERVER_NAME }}:35357'}
    - { backup : no,   section : 'keystone_authtoken', option : 'memcached_servers'  , value : '{{ MEMCACHED_SERVER_NAME }}:11211'}
    - { backup : no,   section : 'keystone_authtoken', option : 'auth_type'          , value : 'password'}
    - { backup : no,   section : 'keystone_authtoken', option : 'project_domain_name', value : 'default'}
    - { backup : no,   section : 'keystone_authtoken', option : 'user_domain_name'   , value : 'default'}
    - { backup : no,   section : 'keystone_authtoken', option : 'project_name'       , value : 'service'}
    - { backup : no,   section : 'keystone_authtoken', option : 'username'           , value : 'manila'}
    - { backup : no,   section : 'keystone_authtoken', option : 'password'           , value : '{{ MANILA_PASSWORD }}'}
    - { backup : no,   section : 'DEFAULT'           , option : 'my_ip'              , value : '{{ ansible_default_ipv4.address }}'}
    - { backup : no,   section : 'oslo_concurrency'  , option : 'lock_path'          , value : '/var/lib/manila/tmp'}

- name: Populate the Manila database
  shell: "{{ item }}"
  with_items:
    - manila-manage db sync

- name: Restart the Cinder service
  service:
    state: restarted
    name: "{{ item }}"
  with_items:
    - manila-scheduler
    - manila-api
