---
# tasks file for setup_neutron_compute
- name: Install neutron compute packages
  apt: pkg={{ item }}
  with_items:
    - neutron-linuxbridge-agent

- name: Configure neutron.conf file
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: "{{item.section}}"
    option:  "{{item.option}}"
    value:   "{{item.value}}"
    backup:  "{{item.backup}}"
  with_items:
    - { backup : yes,  section : 'DEFAULT'           , option : 'rpc_backend'        , value: 'rabbit'}
    - { backup : no,   section : 'oslo_messaging_rabbit', option : 'rabbit_host'     , value: '{{ RABBITMQ_SERVER }}'}
    - { backup : no,   section : 'oslo_messaging_rabbit', option : 'rabbit_userid'   , value: '{{ RABBITMQ_USER }}'}
    - { backup : no,   section : 'oslo_messaging_rabbit', option : 'rabbit_password' , value: '{{ RABBITMQ_PASSWORD}}'}
    - { backup : no,   section : 'DEFAULT'           , option : 'auth_strategy'      , value : 'keystone'}
    - { backup : no,   section : 'keystone_authtoken', option : 'auth_uri'           , value : 'http://{{ KEYSTONE_SERVER_NAME }}:5000'}
    - { backup : no,   section : 'keystone_authtoken', option : 'auth_url'           , value : 'http://{{ KEYSTONE_SERVER_NAME }}:35357'}
    - { backup : no,   section : 'keystone_authtoken', option : 'memcached_servers'  , value : '{{ MEMCACHED_SERVER_NAME }}:11211'}
    - { backup : no,   section : 'keystone_authtoken', option : 'auth_type'          , value : 'password'}
    - { backup : no,   section : 'keystone_authtoken', option : 'project_domain_name', value : 'default'}
    - { backup : no,   section : 'keystone_authtoken', option : 'user_domain_name'   , value : 'default'}
    - { backup : no,   section : 'keystone_authtoken', option : 'project_name'       , value : 'service'}
    - { backup : no,   section : 'keystone_authtoken', option : 'username'           , value : 'neutron'}
    - { backup : no,   section : 'keystone_authtoken', option : 'password'           , value : '{{ NEUTRON_PASSWORD }}'}

- name: Configure linuxbridge_agent.ini file
  ini_file:
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: "{{item.section}}"
    option:  "{{item.option}}"
    value:   "{{item.value}}"
    backup:  "{{item.backup}}"
  with_items:
    - { backup : yes,  section : 'linux_bridge'  , option : 'physical_interface_mappings' , value: 'provider:{{ INTERFACE_NAME }}'}
    - { backup : no,   section : 'vxlan'         , option : 'enable_vxlan'                , value: 'True'}
    - { backup : no,   section : 'vxlan'         , option : 'local_ip'                    , value: '{{ ansible_default_ipv4.address }}'}
    - { backup : no,   section : 'vxlan'         , option : 'l2_population'               , value: 'True'}
    - { backup : no,   section : 'securitygroup' , option : 'enable_security_group'       , value: 'True'}
    - { backup : no,   section : 'securitygroup' , option : 'firewall_driver'             , value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver'}

- name: Configure nova.conf file
  ini_file:
    dest: /etc/nova/nova.conf
    section: "{{item.section}}"
    option:  "{{item.option}}"
    value:   "{{item.value}}"
    backup:  "{{item.backup}}"
  with_items:
    - { backup : yes,  section : 'neutron', option : 'url'                    , value : 'http://{{ NEUTRON_SERVER_NAME }}:9696'}
    - { backup : no,   section : 'neutron', option : 'auth_url'               , value : 'http://{{ KEYSTONE_SERVER_NAME }}:35357'}
    - { backup : no,   section : 'neutron', option : 'auth_type'              , value : 'password'}
    - { backup : no,   section : 'neutron', option : 'project_domain_name'    , value : 'default'}
    - { backup : no,   section : 'neutron', option : 'user_domain_name'       , value : 'default'}
    - { backup : no,   section : 'neutron', option : 'region_name'            , value : 'RegionOne'}
    - { backup : no,   section : 'neutron', option : 'project_name'           , value : 'service'}
    - { backup : no,   section : 'neutron', option : 'username'               , value : 'neutron'}
    - { backup : no,   section : 'neutron', option : 'password'               , value : '{{ NEUTRON_PASSWORD }}'}

- name: Restart the Neutron service
  service:
    state: restarted
    name: "{{ item }}"
  with_items:
    - nova-compute
    - neutron-linuxbridge-agent
